### ISSUE TITLE
Erreur 404

### ISSUE THREAD

**Issue by djibe** [betagouv/api-medicaments#23]
Bonjour, le lien vers la page du projet donne une erreur 404.

Y a t il une page à jour pour détailler l'API ?

**Comment by jdesboeufs** [comment]
Bonjour,

Cette API n'est actuellement plus maintenue.
L'équipe qui l'a développé il y a quelques années n'a pas réussi à convaincre l'ANSM.

Nous l'avons depuis retiré de api.gouv.fr

**Comment by djibe** [comment]
@jdesboeufs 
Merci beaucoup pour cette réponse claire ;-)
Qué dommache !
